[project]
name = "icloud-photo-sync"
version = "0.1.0"
description = "A tool to sync photos from iCloud to local storage with deletion tracking"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { file = "LICENSE" }
keywords = ["icloud", "photos", "sync", "backup"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "pyicloud>=2.0.1",
    "python-dotenv>=1.1.1",
]

[project.scripts]
icloud-photo-sync = "icloud_photo_sync.main:main"

[project.urls]
Homepage = "https://github.com/your-username/icloud-photo-sync"
Repository = "https://github.com/your-username/icloud-photo-sync"
Issues = "https://github.com/your-username/icloud-photo-sync/issues"

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.2",
]
