name: Nightly Builds and Extended Tests

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  extended-tests:
    name: Extended Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --dev

    - name: Create .env file for testing
      run: |
        cp .env.example .env
        echo "✓ Created .env file from .env.example for testing"

    - name: Run extended test suite
      timeout-minutes: 17
      run: |
        uv run pytest -m "not manual" --tb=long --verbose --timeout=300

    - name: Test build process (Linux/macOS)
      if: runner.os != 'Windows'
      timeout-minutes: 8
      run: |
        chmod +x build_linux.sh
        ./build_linux.sh --test

    - name: Test build process (Windows)
      if: runner.os == 'Windows'
      timeout-minutes: 8
      run: |
        powershell -ExecutionPolicy Bypass -File build_windows.ps1 -Test

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: nightly-build-${{ matrix.os }}
        path: dist/

  performance-tests:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Create .env file for testing
      run: |
        cp .env.example .env
        echo "✓ Created .env file from .env.example for testing"

    - name: Run performance tests
      run: |
        # Add performance test script when available
        echo "Performance tests would run here"
        # uv run pytest tests/performance/ --benchmark-only

    - name: Memory usage test
      run: |
        uv run python -c "
        import sys
        try:
            import psutil
            import subprocess
            import time
            
            print('🔍 Testing memory usage...')
            
            # Test memory usage of a simple Python process
            process = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(3)'])
            
            try:
                initial_memory = psutil.Process(process.pid).memory_info().rss / 1024 / 1024
                time.sleep(1)
                final_memory = psutil.Process(process.pid).memory_info().rss / 1024 / 1024
                
                print(f'Initial memory: {initial_memory:.2f} MB')
                print(f'Final memory: {final_memory:.2f} MB')
                print(f'Memory delta: {final_memory - initial_memory:.2f} MB')
                print('✅ Memory usage test completed successfully')
            except Exception as e:
                print(f'⚠️  Memory monitoring error: {e}')
            finally:
                process.terminate()
                process.wait()
                
        except ImportError as e:
            print(f'❌ Missing dependency: {e}')
            print('💡 psutil should be available in dev dependencies')
            sys.exit(1)
        except Exception as e:
            print(f'❌ Memory test failed: {e}')
            sys.exit(1)
        "

  compatibility-tests:
    name: Compatibility Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-2022]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Create .env file for testing
      run: |
        cp .env.example .env
        echo "✓ Created .env file from .env.example for testing"

    - name: Run unit tests
      timeout-minutes: 8
      run: |
        echo "Running unit tests..."
        uv run pytest tests/unit/ -v

    - name: Run integration tests (fast)
      timeout-minutes: 8
      run: |
        echo "Running fast integration tests..."
        uv run pytest tests/integration/ -k "not slow" -v --cov-fail-under=25

    - name: Test executable compatibility (Linux)
      if: runner.os == 'Linux'
      timeout-minutes: 5
      run: |
        chmod +x build_linux.sh
        ./build_linux.sh
        timeout 30s ./dist/iphoto_downloader --help || echo "Executable help test completed"

    - name: Test executable compatibility (Windows)
      if: runner.os == 'Windows'
      timeout-minutes: 5
      run: |
        powershell -ExecutionPolicy Bypass -File build_windows.ps1
        # Set a timeout for the executable test
        $job = Start-Job -ScriptBlock { & "dist\iphoto_downloader.exe" --help }
        if (Wait-Job $job -Timeout 30) {
          Receive-Job $job
          Write-Host "Executable help test completed"
        } else {
          Stop-Job $job
          Write-Host "Executable test timed out (expected in CI)"
        }
        Remove-Job $job -Force

  notify-results:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [extended-tests, performance-tests, compatibility-tests]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Evaluate results
      run: |
        echo "Extended tests: ${{ needs.extended-tests.result }}"
        echo "Performance tests: ${{ needs.performance-tests.result }}"
        echo "Compatibility tests: ${{ needs.compatibility-tests.result }}"
        
        if [[ "${{ needs.extended-tests.result }}" == "failure" ]] || \
           [[ "${{ needs.performance-tests.result }}" == "failure" ]] || \
           [[ "${{ needs.compatibility-tests.result }}" == "failure" ]]; then
          echo "Some nightly tests failed - consider investigating"
          exit 1
        else
          echo "All nightly tests passed successfully"
        fi

    - name: Create issue on failure
      if: failure() && github.event_name == 'schedule'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🚨 Nightly build failure - ${new Date().toISOString().split('T')[0]}`,
            body: `## 🚨 Nightly Build Failure
            
            The nightly build and extended test suite has failed.
            
            **Failure Details:**
            - Extended tests: ${{ needs.extended-tests.result }}
            - Performance tests: ${{ needs.performance-tests.result }}
            - Compatibility tests: ${{ needs.compatibility-tests.result }}
            
            **Action Required:**
            Please investigate the failing tests and address any issues.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            This issue was automatically created by the nightly build workflow.`,
            labels: ['bug', 'ci/cd', 'nightly-failure']
          })
