name: Release - Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run tests before building
      run: |
        uv run pytest -m "not manual" --tb=short

    - name: Build Windows executables
      run: |
        powershell -ExecutionPolicy Bypass -File build_windows.ps1

    - name: Test built executables
      run: |
        uv run python test_build.py --quick

    - name: Create Windows artifacts directory
      run: |
        mkdir windows-artifacts
        copy dist\iphoto_downloader.exe windows-artifacts\
        copy dist\manage_credentials.exe windows-artifacts\

    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: windows-artifacts/

  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run tests before building
      run: |
        uv run pytest -m "not manual" --tb=short

    - name: Build Linux executables
      run: |
        chmod +x build_linux.sh
        ./build_linux.sh

    - name: Test built executables
      run: |
        uv run python test_build.py --quick

    - name: Create Linux artifacts directory
      run: |
        mkdir linux-artifacts
        cp dist/iphoto_downloader linux-artifacts/
        cp dist/manage_credentials linux-artifacts/

    - name: Upload Linux build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-executables
        path: linux-artifacts/

  package-apt:
    name: Package for APT Repository
    runs-on: ubuntu-latest
    needs: build-linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux executables
      uses: actions/download-artifact@v4
      with:
        name: linux-executables
        path: linux-executables/

    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper devscripts

    - name: Create Debian package structure
      run: |
        mkdir -p debian-package/iphoto-downloader/DEBIAN
        mkdir -p debian-package/iphoto-downloader/usr/bin
        mkdir -p debian-package/iphoto-downloader/usr/share/doc/iphoto-downloader
        mkdir -p debian-package/iphoto-downloader/usr/share/applications

    - name: Copy executables to package
      run: |
        cp linux-executables/iphoto_downloader debian-package/iphoto-downloader/usr/bin/
        cp linux-executables/manage_credentials debian-package/iphoto-downloader/usr/bin/iphoto-downloader-credentials
        chmod +x debian-package/iphoto-downloader/usr/bin/*

    - name: Create Debian control file
      run: |
        cat > debian-package/iphoto-downloader/DEBIAN/control << EOF
        Package: iphoto-downloader
        Version: ${{ github.event.release.tag_name || github.event.inputs.version }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: iPhoto Downloader Team <team@iPhotoDownloader.example.com>
        Description: iPhoto Downloader Tool
         A tool for synchronizing photos from iCloud to local storage with
         intelligent deletion tracking and album filtering capabilities.
         .
         Features include:
         - Bidirectional sync with iCloud Photos
         - Smart deletion tracking to prevent re-downloads
         - Album-based filtering and organization
         - 2FA authentication support with Pushover notifications
         - Cross-platform compatibility
        Depends: libc6, libssl3
        Homepage: https://github.com/HenningUe/iphoto-downloader
        EOF

    - name: Create desktop entry
      run: |
        cat > debian-package/iphoto-downloader/usr/share/applications/iphoto-downloader.desktop << EOF
        [Desktop Entry]
        Name=iPhoto Downloader
        Comment=iPhoto Downloader Tool
        Exec=/usr/bin/iphoto_downloader
        Icon=iphoto-downloader
        Terminal=true
        Type=Application
        Categories=Graphics;Photography;
        EOF

    - name: Copy documentation
      run: |
        cp README.md debian-package/iphoto-downloader/usr/share/doc/iphoto-downloader/
        cp LICENSE debian-package/iphoto-downloader/usr/share/doc/iphoto-downloader/copyright

    - name: Build Debian package
      run: |
        cd debian-package
        dpkg-deb --build iphoto-downloader
        mv iphoto-downloader.deb ../iphoto-downloader_${{ github.event.release.tag_name || github.event.inputs.version }}_amd64.deb

    - name: Upload APT package artifact
      uses: actions/upload-artifact@v4
      with:
        name: apt-package
        path: iphoto-downloader_*.deb

  package-winget:
    name: Package for WinGet
    runs-on: windows-latest
    needs: build-windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows executables
      uses: actions/download-artifact@v4
      with:
        name: windows-executables
        path: windows-executables/

    - name: Install WinGet Create
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate.exe" -OutFile "wingetcreate.exe"

    - name: Create WinGet package manifest
      run: |
        $version = "${{ github.event.release.tag_name || github.event.inputs.version }}"
        $version = $version -replace '^v', ''  # Remove 'v' prefix if present
        
        # Create installer for main executable
        $mainSize = (Get-Item windows-executables/iphoto_downloader.exe).Length
        $credSize = (Get-Item windows-executables/manage_credentials.exe).Length
        
        # Create manifest directory
        New-Item -ItemType Directory -Force -Path "winget-manifests"
        
        # Create version manifest
        $versionManifest = @"
        PackageIdentifier: HenningUe.iPhotoDownloader
        PackageVersion: $version
        DefaultLocale: en-US
        ManifestType: version
        ManifestVersion: 1.2.0
        "@
        
        # Create installer manifest
        $installerManifest = @"
        PackageIdentifier: HenningUe.iPhotoDownloader
        PackageVersion: $version
        Installers:
        - Architecture: x64
          InstallerType: exe
          InstallerUrl: https://github.com/HenningUe/iphoto-downloader/releases/download/${{ github.event.release.tag_name || github.event.inputs.version }}/iphoto_downloader.exe
          InstallerSha256: # Will be calculated by WinGet team
          InstallerSwitches:
            Silent: ""
            SilentWithProgress: ""
        ManifestType: installer
        ManifestVersion: 1.2.0
        "@
        
        # Create locale manifest
        $localeManifest = @"
        PackageIdentifier: HenningUe.iPhotoDownloader
        PackageVersion: $version
        PackageLocale: en-US
        Publisher: HenningUe
        PublisherUrl: https://github.com/HenningUe
        PublisherSupportUrl: https://github.com/HenningUe/iphoto-downloader/issues
        Author: HenningUe
        PackageName: iPhoto Downloader
        PackageUrl: https://github.com/HenningUe/iphoto-downloader
        License: MIT
        LicenseUrl: https://github.com/HenningUe/iphoto-downloader/blob/main/LICENSE
        Copyright: Copyright (c) HenningUe
        ShortDescription: iPhoto Downloader Tool with intelligent deletion tracking
        Description: A comprehensive tool for synchronizing photos from iCloud to local storage with smart deletion tracking, album filtering, and 2FA support.
        Moniker: iphoto-downloader
        Tags:
        - icloud
        - photos
        - sync
        - backup
        - photo-management
        ManifestType: defaultLocale
        ManifestVersion: 1.2.0
        "@
        
        # Save manifests
        $versionManifest | Out-File -FilePath "winget-manifests/HenningUe.iPhotoDownloader.yaml" -Encoding UTF8
        $installerManifest | Out-File -FilePath "winget-manifests/HenningUe.iPhotoDownloader.installer.yaml" -Encoding UTF8
        $localeManifest | Out-File -FilePath "winget-manifests/HenningUe.iPhotoDownloader.locale.en-US.yaml" -Encoding UTF8

    - name: Upload WinGet manifests
      uses: actions/upload-artifact@v4
      with:
        name: winget-manifests
        path: winget-manifests/

  publish-to-winget:
    name: Publish to WinGet
    runs-on: windows-latest
    needs: [package-winget, publish-release]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download WinGet manifests
      uses: actions/download-artifact@v4
      with:
        name: winget-manifests
        path: winget-manifests/

    - name: Submit to WinGet Community Repository
      run: |
        # This step would typically involve:
        # 1. Forking the Microsoft/winget-pkgs repository
        # 2. Creating a PR with the new manifests
        # 3. Submitting for review
        
        Write-Host "WinGet manifests prepared for submission"
        Write-Host "Manual step required: Submit PR to microsoft/winget-pkgs repository"
        
        # For now, we'll just display the manifest contents
        Get-ChildItem winget-manifests/ -Filter "*.yaml" | ForEach-Object {
            Write-Host "=== $($_.Name) ==="
            Get-Content $_.FullName
        }

  publish-to-apt:
    name: Publish to APT Repository
    runs-on: ubuntu-latest
    needs: [package-apt, publish-release]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download APT package
      uses: actions/download-artifact@v4
      with:
        name: apt-package
        path: apt-package/

    - name: Prepare APT repository submission
      run: |
        echo "APT package prepared for submission"
        echo "Package details:"
        dpkg-deb --info apt-package/*.deb
        
        echo "Manual step required:"
        echo "1. Submit package to appropriate APT repository"
        echo "2. Follow repository-specific submission guidelines"
        echo "3. Package available at: apt-package/"
        
        ls -la apt-package/

  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows executables
      uses: actions/download-artifact@v4
      with:
        name: windows-executables
        path: windows-executables/

    - name: Download Linux executables
      uses: actions/download-artifact@v4
      with:
        name: linux-executables
        path: linux-executables/

    - name: Create release assets
      run: |
        mkdir release-assets
        
        # Package Windows executables
        cd windows-executables
        zip ../release-assets/iphoto-downloader-windows-x64.zip *
        cd ..
        
        # Package Linux executables
        cd linux-executables
        tar -czf ../release-assets/iphoto-downloader-linux-x64.tar.gz *
        cd ..
        
        # Copy individual executables with versioned names
        cp windows-executables/iphoto_downloader.exe release-assets/
        cp windows-executables/manage_credentials.exe release-assets/
        cp linux-executables/iphoto_downloader release-assets/
        cp linux-executables/manage_credentials release-assets/iphoto-downloader-credentials

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-assets/*
        body: |
          ## 🚀 Release ${{ github.event.release.tag_name }}
          
          ### Downloads
          
          **Windows:**
          - 📦 [Complete Windows Package](./iphoto-downloader-windows-x64.zip) - Both executables in one ZIP
          - 🖼️ [Main Application (iphoto_downloader.exe)](./iphoto_downloader.exe)
          - 🔐 [Credentials Manager (manage_credentials.exe)](./manage_credentials.exe)
          
          **Linux:**
          - 📦 [Complete Linux Package](./iphoto-downloader-linux-x64.tar.gz) - Both executables in one archive
          - 🖼️ [Main Application (iphoto_downloader)](./iphoto_downloader)
          - 🔐 [Credentials Manager (iphoto-downloader-credentials)](./iphoto-downloader-credentials)
          
          ### Installation
          
          **Windows (via WinGet):**
          ```powershell
          winget install HenningUe.iPhotoDownloader
          ```
          
          **Linux (via APT):**
          ```bash
          # APT repository submission in progress
          # Manual installation for now:
          wget https://github.com/HenningUe/iphoto-downloader/releases/download/${{ github.event.release.tag_name }}/iphoto-downloader-linux-x64.tar.gz
          tar -xzf iphoto-downloader-linux-x64.tar.gz
          sudo mv iphoto_downloader /usr/local/bin/
          sudo mv manage_credentials /usr/local/bin/iphoto-downloader-credentials
          ```
          
          ### What's New
          - Full CI/CD pipeline with automatic builds
          - Cross-platform executable distribution
          - Preparation for WinGet and APT package managers
          
          ### Getting Started
          1. Download the appropriate executable for your platform
          2. Run the credentials manager first to set up your iCloud credentials
          3. Configure your sync settings
          4. Start syncing your photos!
          
          For detailed instructions, see the [README](https://github.com/HenningUe/iphoto-downloader/blob/main/README.md).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
